import { z } from "zod";

const clientEnvSchema = z.object({
  NEXT_PUBLIC_KAKAO_JAVASCRIPT_KEY: z.string(),
  NEXT_PUBLIC_URL: z.string(),
  NEXT_PUBLIC_KAKAO_REDIRECT_URI: z.string(),
  NEXT_PUBLIC_KAKAO_REST_API_KEY: z.string(),
  NEXT_PUBLIC_KAKAO_CLIENT_ID: z.string(),
  NEXT_PUBLIC_KAKAO_LOGOUT_URI: z.string(),
});

const clientEnv = clientEnvSchema.parse({
  NEXT_PUBLIC_KAKAO_JAVASCRIPT_KEY:
    process.env.NEXT_PUBLIC_KAKAO_JAVASCRIPT_KEY,
  NEXT_PUBLIC_URL: process.env.NEXT_PUBLIC_URL,
  NEXT_PUBLIC_KAKAO_REST_API_KEY: process.env.NEXT_PUBLIC_KAKAO_REST_API_KEY,
  NEXT_PUBLIC_KAKAO_REDIRECT_URI: process.env.NEXT_PUBLIC_KAKAO_REDIRECT_URI,
  NEXT_PUBLIC_KAKAO_CLIENT_ID: process.env.NEXT_PUBLIC_KAKAO_CLIENT_ID,
  NEXT_PUBLIC_KAKAO_LOGOUT_URI: process.env.NEXT_PUBLIC_KAKAO_LOGOUT_URI,
});

export default clientEnv;
